name: Periodic build
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - 'feature/periodic-build-feedback'

jobs:
  notify-start:
    name: Notify release start
    uses: ho-nl/release-slack-action/.github/workflows/notify-slack-start.yml@main
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN }}
    with:
      channel: slack-test-messages
      message: Graphcommerce start building
      notifyOnlyOnFailure: true

  publish:
    strategy:
      matrix:
        version: [18, 20, 22]
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: graphcommerce

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
          scope: 'graphcommerce'

      - name: Prepare and build graphcommerce
        run: |
          cp -R graphcommerce/examples/magento-graphcms/. graphcommerce-build 
          cd graphcommerce-build 
          corepack enable
          yarn
          yarn codegen
          yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set job output based on result
        id: set-output
        run: |
          if [ "${{ job.status }}" == "failure" ]; then
            echo "Job failed for Node.js version: ${{ matrix.version }}"
            echo "::set-output name=result::Node.js version ${{ matrix.version }}: failed"
          else
            echo "::set-output name=result::Node.js version ${{ matrix.version }}: succeeded"
          fi

  aggregate-results:
    if: always()
    needs: publish
    runs-on: ubuntu-latest
    outputs:
      failed-jobs: ${{ steps.aggregate-failures.outputs.failed-jobs }}
    steps:
      - name: Aggregate failure results
        id: aggregate-failures
        run: |
          echo "Collecting matrix results..."
          failed_jobs=""
          for job in "${{ needs.publish.outputs.result }}"; do
            if [[ "$job" == *failed* ]]; then
              failed_jobs="$failed_jobs\n$job"
            fi
          done

          if [ -z "$failed_jobs" ]; then
            echo "No failed jobs detected."
          else
            echo "Failed jobs detected: $failed_jobs"
          fi

          echo "::set-output name=failed-jobs::$failed_jobs"

  notify-end:
    if: always()
    needs: [notify-start, publish, aggregate-results]
    name: Notify release end
    uses: ho-nl/release-slack-action/.github/workflows/notify-slack-end.yml@main
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN }}
    with:
      time: ${{ needs.notify-start.outputs.time }}
      channel: slack-test-messages
      message: |
        Periodic build results:
        ${{ needs.aggregate-results.outputs.failed-jobs }}
      notifyOnlyOnFailure: true
