name: Periodic build
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - 'feature/periodic-build-feedback'

jobs:
  notify-start:
    name: Notify release start
    uses: ho-nl/release-slack-action/.github/workflows/notify-slack-start.yml@main
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN }}
    with:
      channel: slack-test-messages
      message: Graphcommerce start building
      notifyOnlyOnFailure: true

  publish:
    strategy:
      matrix:
        version: [18, 20, 22]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: graphcommerce

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
          scope: 'graphcommerce'

      - name: Prepare and build graphcommerce
        run: |
          cp -R graphcommerce/examples/magento-graphcms/. graphcommerce-build 
          cd graphcommerce-build 
          corepack enable
          yarn
          yarn codegen
          yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  report-failures:
    if: always()
    needs: publish
    runs-on: ubuntu-latest
    outputs:
      failed-jobs: ${{ steps.aggregate-failures.outputs.failed-jobs }}
    steps:
      - name: Aggregate failure results
        id: aggregate-failures
        run: |
          echo "Checking for failed matrix jobs..."
          failed_jobs=""
          for job in "${{ toJSON(needs.publish.strategy) }}"
          do
            if [ "${{ job.result }}" == "failure" ]; then
              failed_jobs="$failed_jobs\nJob with Node.js version ${{ job.matrix.version }} failed."
            fi
          done
          echo "Failed jobs: $failed_jobs"
          echo "::set-output name=failed-jobs::$failed_jobs"

  notify-end:
    if: always()
    needs: [notify-start, publish, report-failures]
    name: Notify release end
    uses: ho-nl/release-slack-action/.github/workflows/notify-slack-end.yml@main
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN }}
    with:
      time: ${{ needs.notify-start.outputs.time }}
      result: ${{ needs.publish.result }}
      channel: slack-test-messages
      message: |
        Periodic build results:
        ${{ needs.report-failures.outputs.failed-jobs }}
      notifyOnlyOnFailure: true
